import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { Fragment } from "react";
import Footer from "../components/footer";
import Header from "../components/header";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Fragment>
      <Head>
        <title>Pre Launcher</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <section className="hero vh-100 border-bottom">
          <div className="container text-center pt-5 px-4">
            <div className="hero-content mb-5">
              <h1 className="main-title mb-4">
                Lorem ipsum dolor sit amet consectetur adipisicing elit.
              </h1>
              <p className="subtitle mb-4">
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua
              </p>
              <button className="btn main-button">Order Now!</button>
            </div>
            <div className="sample-box bg-secondary"></div>
          </div>
        </section>

        <section className="navigation border-bottom mb-5">
          <nav className="container d-flex py-4 px-4">
            <div className="nav-items d-flex overflow-x-auto">
              <Link href="#">
                <a className="nav-link me-5">Campaign</a>
              </Link>
              <Link href="/faq">
                <a className="nav-link me-5">FAQ</a>
              </Link>
              <Link href="/updates">
                <a className="nav-link me-5">Updates</a>
              </Link>
              <Link href="/comments">
                <a className="nav-link me-5">Comments</a>
              </Link>
              <Link href="/community">
                <a className="nav-link me-5">Community</a>
              </Link>
            </div>
          </nav>
        </section>

        <section className="campaign">
          <div className="container px-4">
            <div className="row gx-5">
              <div className="col-lg-8">
                <div className="sample-box bg-secondary mb-2"></div>
                <h2 className="second-title mb-4">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                </h2>
                <h5>Story</h5>
                <p className="description fw-semibold">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Earum, sequi.
                </p>
                <p className="description fw-semibold">
                  Lorem ipsum dolor sit, amet consectetur adipisicing elit.
                  Architecto, unde, maiores provident dolorem iure alias vel,
                  nobis at placeat quidem non dolore incidunt commodi neque!
                </p>
                <p className="description">
                  Lorem ipsum dolor sit amet consectetur adipisicing elit.
                  Eveniet aliquid, cupiditate eligendi rem ratione dignissimos
                  expedita culpa deserunt, quaerat nobis sint porro, dolores
                  perferendis sequi unde corporis itaque non iusto dolor!
                  Excepturi eius nam est?
                </p>
              </div>
              <div className="col-lg-4">
                <div className="border"></div>
              </div>
            </div>
          </div>
        </section>
      </main>

      <Footer />
    </Fragment>
  );
}
